version: '3.8'

services:
  app:
    build: .
    container_name: flask_app
    ports:
      - "5050:5000"
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - DEBUG=${DEBUG}
      - PORT=${PORT}
      - MONGODB_HOST=${MONGODB_HOST}
      - MONGODB_PORT=${MONGODB_PORT}
      - MONGODB_DB=${MONGODB_DB}
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:6
    container_name: visitor_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
